---

- name: Basic playbook for a Workflow
  hosts: all
  gather_facts: no
  tasks:

    - name: Debug ansible_hostname variable
      debug:
        msg: "Managed node: {{ ansible_host }}"
  
    - name: Ping Managed Nodes
      ping: 

    - name: Store my_data value to pass to job2
      set_stats:
        data:
          my_data:
            #"{{ {ansible_host: ansible_host} }}"
            "{{ [ansible_host: ansible_host] }}"
